export const backdropColor = 'rgba(38, 59, 91, 0.8)';

export const errorMessages = {
  1001: "Couldn't find a face on the photo",
  1002: 'Blue is detected on the photo.\n\nPlease try again on a well lit environment',
  1003: 'Glare is detected on the photo.\n\nPlease check the ligting conditions while taking photo',
  1004: "We couldn't crop the document.\n\nPlease try again on a less colored surface",
  1005: 'This document is not supported.\n\nPlease try again',
  1008: 'This document does not belong to your profile.\n\nPlease a document that belongs to you',
  1009: '*** This is for checker message from studio will not shown to user ***',
  2001: 'Your Selfie not matching with your identification document.\n\nPlease try again',
  2002: 'This selfie is not live',
  2003: 'Please look at the kamera while taking selfie',
  3001: 'This document is not live.\n\nPlease try again',
  3002: 'This document is expired.\n\nYou can not use this document',
  4001: 'This document is expired.\n\nPlease try again with another document',
  4002: 'The name on the document is not matching with the ID.\n\nPlease try again',
  5001: 'The signature is not matching with the one in your ID.\n\nPlease try again',
  6001: 'The signature in your contract is not matching with the one in your ID.\n\nPlease try again',
};

export const eventDescriptions = {
  TouchEvent: 'kullanici ekrana dokundu',
  IDSelection: 'kimlik tipi secme',
  IDSelection_YeniTC: 'yeni tc kimlik tiklama',
  IDSelection_EskiTC: 'eski tc kimlik tiklama',
  IDSelection_YeniE: 'yeni ehliyet tiklama',
  ID_On_Cek: 'kimlik on yuz fotosu icin deklansor butonuna tiklama',
  ID_On_Err_Blur: 'kimlik on yuz fotosu autocapture - blur hatasi',
  ID_On_Err_Glare: 'kimlik on yuz fotosu autocapture - glare hatasi',
  ID_On_Err_BG: 'kimlik on yuz fotosu autocapture - background hatasi',
  ID_On_Err_TCKN:
    'kimlik on yuz fotosu autocapture - baskasina ait tckn hatasi',
  ID_On_Onay: 'kimlik on yuz fotosu "onayla" butonuna tiklama',
  ID_Arka_Cek: 'kimlik arka yuz fotosu icin deklansor butonuna tiklama',
  ID_Arka_Onay: 'kimlik arka yuz fotosu "onayla" butonuna tiklama',
  ID_Success_Dvm: 'kimlik tebrikler sayfasında devam butonuna tiklama',
  ID_Err_Liveness: 'kimlik validasyon - liveness hatasi',
  ID_Err_Expiry: 'kimlik validasyon - expiry date hatasi',
  Selfie_Cek: 'selfie fotosu için deklansor butonuna tiklama',
  Selfie_Onay: 'selfie "onayla" butonuna tiklama',
  Selfie_Success_Dvm: 'selfie tebrikler sayfasında devam butonuna tiklama',
  Adres_Ftr: 'fatura kurum secme',
  Adres_Ikm: 'ikametgah belgesi secme',
  Adres_Atla: 'adres adimini atla butonuna tiklama',
  Fatura_Cek: 'fatura fotosu icin deklansor butonuna tiklama',
  Fatura_Pdf: 'fatura pdf yukle butonuna tiklama',
  Ikm_Cek: 'ikamet yukle sayfasinda fotosu icin deklansor butonuna tiklama',
  Ikm_Pdf: 'ikamet yukle sayfasinda pdf butonuna tiklama',
  Ikm_Edev: 'ikamet yukle sayfasinda edevlet butonuna tiklama',
  Ikm_Edev_Al: 'ikamet e-devletten al butonuna tiklama',
  Ikm_Onay: 'ikamet fotosu "onayla" butonuna tiklama',
  Adres_Dvm: 'adres yukleme success sayfasinda devam butonuna tiklama',
  Dijital_Onay: 'dijital sozlesme onayla butonuna tiklama',
  Imza1_Onay: '1. imza onayla butonuna tiklama',
  Imza2_Onay: '2. imza onayla butonuna tiklama',
  Fzk_Ind: 'sozlesmeni indir butonuna tiklama',
  Fzk_Eposta: 'sozlesmeni eposta ile gonder butonuna tiklama',
  Fzk_Eposta_Gnd: 'eposta popupinda gonder butonuna tiklama',
  Fzk_FotoCek: 'sozlesmenin fotografini cek butonuna tiklama',
  Fzk_Cek: 'fiziksel sozlesme fotosu icin deklansor butonuna tiklama',
  Fzk_Pdf: 'fiziksel sozlesme pdf yukle butonuna tiklama',
  Fzk_Onay: 'fiziksel sozlesme fotosu "onayla" butonuna tiklama',
  Fzk_Dvm: 'fiziksel sozlesme tebrikler sayfasında devam butonuna tiklama',
  Eksik_Adim_VIEW: 'amani overview sayfasi goruntuleme',
  Eksik_Adim_CLICK: 'amani overview sayfasinda eksik adimlardan birini tiklama',
};
