export const backdropColor = 'rgba(38, 59, 91, 0.8)';

export const errorMessages = {
  1001: 'Fotoğrafta yüz bulunamadı',
  1002: 'Fotoğrafta bulanıklık tespit edildi.\n\nLütfen daha iyi aydınlatılmış bir ortamda tekrar dene',
  1003: 'Fotoğrafta parlama tespit edildi.\n\nLütfen belgenin üstüne doğrudan ışık gelmemesine dikkat et',
  1004: 'Belgeyi arka plandan ayrıştıramadık.\n\nLütfen tek renk bir yüzey üzerinde tekrar dene',
  1005: 'Bu belge tipi desteklenmiyor.\n\nLütfen tekrar dene',
  1008: 'Bu kimlik sana ait değil.\n\nLütfen kendine ait bir kimlik kullan',
  2001: 'Selfie kimlik belgendeki fotoğrafla uyuşmuyor.\n\nLütfen tekrar dene',
  2002: 'Lütfen gerçek bir selfie çek',
  2003: 'Lütfen selfie çekerken doğrudan kameraya bak',
  3001: 'Belge geçerli değil.\n\nLütfen tekrar dene',
  3002: 'Kimliğin süresi geçmiş.\n\nBu belge ile işlem yapılamaz',
  4001: 'Belgenin süresi geçmiş.\n\nLütfen başka bir belge dene',
  4002: 'Belgedeki isim kimlikteki isimle uyuşmuyor.\n\nLütfen tekrar dene',
  5001: 'Attığın imza kimliğindeki imza ile uyuşmuyor.\n\nLütfen tekrar dene',
  6001: 'Sözleşmedeki imzan kimliğindeki imza ile uyuşmuyor.\n\nLütfen tekrar dene',
};

export const eventDescriptions = {
  TouchEvent: 'kullanici ekrana dokundu',
  IDSelection: 'kimlik tipi secme',
  IDSelection_YeniTC: 'yeni tc kimlik tiklama',
  IDSelection_EskiTC: 'eski tc kimlik tiklama',
  IDSelection_YeniE: 'yeni ehliyet tiklama',
  ID_On_Cek: 'kimlik on yuz fotosu icin deklansor butonuna tiklama',
  ID_On_Err_Blur: 'kimlik on yuz fotosu autocapture - blur hatasi',
  ID_On_Err_Glare: 'kimlik on yuz fotosu autocapture - glare hatasi',
  ID_On_Err_BG: 'kimlik on yuz fotosu autocapture - background hatasi',
  ID_On_Err_TCKN:
    'kimlik on yuz fotosu autocapture - baskasina ait tckn hatasi',
  ID_On_Onay: 'kimlik on yuz fotosu "onayla" butonuna tiklama',
  ID_Arka_Cek: 'kimlik arka yuz fotosu icin deklansor butonuna tiklama',
  ID_Arka_Onay: 'kimlik arka yuz fotosu "onayla" butonuna tiklama',
  ID_Success_Dvm: 'kimlik tebrikler sayfasında devam butonuna tiklama',
  ID_Err_Liveness: 'kimlik validasyon - liveness hatasi',
  ID_Err_Expiry: 'kimlik validasyon - expiry date hatasi',
  Selfie_Cek: 'selfie fotosu için deklansor butonuna tiklama',
  Selfie_Onay: 'selfie "onayla" butonuna tiklama',
  Selfie_Success_Dvm: 'selfie tebrikler sayfasında devam butonuna tiklama',
  Adres_Ftr: 'fatura kurum secme',
  Adres_Ikm: 'ikametgah belgesi secme',
  Adres_Atla: 'adres adimini atla butonuna tiklama',
  Fatura_Cek: 'fatura fotosu icin deklansor butonuna tiklama',
  Fatura_Pdf: 'fatura pdf yukle butonuna tiklama',
  Ikm_Cek: 'ikamet yukle sayfasinda fotosu icin deklansor butonuna tiklama',
  Ikm_Pdf: 'ikamet yukle sayfasinda pdf butonuna tiklama',
  Ikm_Edev: 'ikamet yukle sayfasinda edevlet butonuna tiklama',
  Ikm_Edev_Al: 'ikamet e-devletten al butonuna tiklama',
  Ikm_Onay: 'ikamet fotosu "onayla" butonuna tiklama',
  Adres_Dvm: 'adres yukleme success sayfasinda devam butonuna tiklama',
  Dijital_Onay: 'dijital sozlesme onayla butonuna tiklama',
  Imza1_Onay: '1. imza onayla butonuna tiklama',
  Imza2_Onay: '2. imza onayla butonuna tiklama',
  Fzk_Ind: 'sozlesmeni indir butonuna tiklama',
  Fzk_Eposta: 'sozlesmeni eposta ile gonder butonuna tiklama',
  Fzk_Eposta_Gnd: 'eposta popupinda gonder butonuna tiklama',
  Fzk_FotoCek: 'sozlesmenin fotografini cek butonuna tiklama',
  Fzk_Cek: 'fiziksel sozlesme fotosu icin deklansor butonuna tiklama',
  Fzk_Pdf: 'fiziksel sozlesme pdf yukle butonuna tiklama',
  Fzk_Onay: 'fiziksel sozlesme fotosu "onayla" butonuna tiklama',
  Fzk_Dvm: 'fiziksel sozlesme tebrikler sayfasında devam butonuna tiklama',
  Eksik_Adim_VIEW: 'amani overview sayfasi goruntuleme',
  Eksik_Adim_CLICK: 'amani overview sayfasinda eksik adimlardan birini tiklama',
};
